### ISSUE TITLE
SoftLayer 4.0.xでの実行エラー

### ISSUE THREAD

**Issue by hssh** [softlayer-yuba/yuba_cli#3]
SoftLayer 4.0.x にアップデートすると yuba cost 実行時に下記エラー発生

Traceback (most recent call last):
  File "/Users/hssh/.virtualenvs/yuba_cli/bin/yuba", line 9, in <module>
    load_entry_point('yuba-cli==0.1.0', 'console_scripts', 'yuba')()
  File "/Users/hssh/.virtualenvs/yuba_cli/lib/python2.7/site-packages/click/core.py", line 664, in **call**
    return self.main(_args, *_kwargs)
  File "/Users/hssh/.virtualenvs/yuba_cli/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/hssh/.virtualenvs/yuba_cli/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hssh/.virtualenvs/yuba_cli/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hssh/.virtualenvs/yuba_cli/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(_args, *_kwargs)
  File "/Users/hssh/Developments/yuba_cli/yuba.py", line 70, in cost
    result = hsm.verify_order(**param)
  File "/Users/hssh/.virtualenvs/yuba_cli/lib/python2.7/site-packages/SoftLayer/managers/hardware.py", line 271, in verify_order
    create_options = self._generate_create_dict(**kwargs)
TypeError: _generate_create_dict() got an unexpected keyword argument 'ram'

**Comment by hssh** [comment]
下記メソッドのパラメータ仕様変更が原因

SoftLayer.managers.hardware.HardwareManager#_generate_create_dict
https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/managers/hardware.py#L374
